# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build corne nice_nano (sturdy, vi)'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left","corne_right","settings_reset"]'
      alphas: '["azerty"]'
      nav: '["vi"]'
      kconfig: '["CONFIG_ZMK_SLEEP=y\\nCONFIG_ZMK_IDLE_SLEEP_TIMEOUT=5400000\\nCONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5\\nCONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5"]'
